
import { featuredImages } from "../../assets/assets";

export const CATEGORIES = ['All', 'Heritage', 'Festive', 'Modern', 'Shawls'];

export const featuredProducts = [
  {
    id: 1,
    name: 'Dhaka Kurta',
    category: 'Heritage',
    price: 4800,
    originalPrice: null,
    image: featuredImages.F1,
    imageBg: 'linear-gradient(160deg, #7c3f00 0%, #b8860b 60%, #e8c36a 100%)',
    stock: 3,
    isNew: true,
    isSale: false,
  },
  {
    id: 2,
    name: 'Pashmina Wrap',
    category: 'Shawls',
    price: 9800,
    originalPrice: 12500,
    image: featuredImages.F2,
    imageBg: 'linear-gradient(160deg, #f5e6c8 0%, #eedcaa 60%, #d4a843 100%)',
    stock: 8,
    isNew: false,
    isSale: true,
  },
  {
    id: 3,
    name: 'Hakupatasi Set',
    category: 'Festive',
    price: 8200,
    originalPrice: null,
    image: featuredImages.F3,
    imageBg: 'linear-gradient(160deg, #3d0000 0%, #8b1a1a 60%, #c94040 100%)',
    stock: 2,
    isNew: true,
    isSale: false,
  },
  {
    id: 4,
    name: 'Labeda Top',
    category: 'Modern',
    price: 3600,
    originalPrice: null,
    image: featuredImages.F4,
    imageBg: 'linear-gradient(160deg, #2c1a0e 0%, #5c3a1e 60%, #8b6343 100%)',
    stock: 12,
    isNew: false,
    isSale: false,
  },
  {
    id: 5,
    name: 'Muga Silk Saree',
    category: 'Festive',
    price: 15500,
    originalPrice: 18000,
    image: featuredImages.F5,
    imageBg: 'linear-gradient(160deg, #4a3000 0%, #8b6914 60%, #c9a84c 100%)',
    stock: 1,
    isNew: false,
    isSale: true,
  },
  {
    id: 6,
    name: 'Allo Fiber Coat',
    category: 'Modern',
    price: 6200,
    originalPrice: null,
    image: featuredImages.F6,
    imageBg: 'linear-gradient(160deg, #1a2a1a 0%, #2d4a2d 60%, #4a7a4a 100%)',
    stock: 6,
    isNew: true,
    isSale: false,
  },
  {
    id: 7,
    name: 'Bhangra Shawl',
    category: 'Shawls',
    price: 5400,
    originalPrice: null,
    image: featuredImages.F7,
    imageBg: 'linear-gradient(160deg, #1a0a2e 0%, #3d1a6e 60%, #6b3aaa 100%)',
    stock: 9,
    isNew: false,
    isSale: false,
  },
  {
    id: 8,
    name: 'Gunyu Cholo',
    category: 'Heritage',
    price: 7800,
    originalPrice: 9500,
    image: featuredImages.F8,
    imageBg: 'linear-gradient(160deg, #2e0a0a 0%, #6e1a1a 60%, #aa3a3a 100%)',
    stock: 4,
    isNew: false,
    isSale: true,
  },
];